# Generated by Django 4.2.7 on 2023-11-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackcoffer',
            name='added',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='blackcoffer',
            name='published',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
